import streamlit as st
from summary import summarize_text
import pdfplumber

# ----------------- Page Config ----------------- #
st.set_page_config(page_title="LLaMA 3 Summarizer", layout="wide")
st.title(" Text Summarizer using local LLM")
st.subheader("Powered by Ollama + LangChain")
st.markdown("Upload a `.txt` or `.pdf` file and get a summary generated by **LLaMA 3 running locally** via Ollama + LangChain.")

# ----------------- File Upload ----------------- #
uploaded_file = st.file_uploader("📎 Upload a file", type=["txt", "pdf"])

# ----------------- Helper to Extract PDF Text ----------------- #
def extract_text_from_pdf(file) -> str:
    with pdfplumber.open(file) as pdf:
        return "\n\n".join([page.extract_text() or "" for page in pdf.pages]).strip()

# ----------------- Process File ----------------- #
if uploaded_file:
    file_extension = uploaded_file.name.split('.')[-1].lower()

    if file_extension == "txt":
        file_content = uploaded_file.read().decode("utf-8")
    elif file_extension == "pdf":
        file_content = extract_text_from_pdf(uploaded_file)
    else:
        st.error("Unsupported file type!")
        file_content = ""

    if file_content:
        # ----------------- Role Selection ----------------- #
        role = st.selectbox("🤖 Summarize for audience:", ["Professor", "Student", "Novice"], index=1)

        # ----------------- Expandable Raw Text ----------------- #
        with st.expander("📖 Preview of Uploaded Text", expanded=False):
            st.text_area("Click to view raw content", file_content[:10000], height=300)

        # ----------------- Summarization Button ----------------- #
        if st.button("🚀 Summarize with LLaMA 3"):
            with st.spinner("Summarizing using local LLaMA 3..."):
                summary = summarize_text(file_content, role=role)

            st.success("✅ Summary complete!")
            st.markdown("### ✂️ Summary:")

            st.text_area("🪄 Output", summary, height=300)

            # Optional download
            st.download_button("📥 Download Summary", summary, file_name="summary.txt", mime="text/plain")

# ----------------- Footer ----------------- #
st.markdown("""<hr style="margin-top: 50px;"/>
<p style='text-align: center; color: gray;'>Made with ❤️ by <a href='https://github.com/Harish9215' target='_blank' style='text-decoration: none; color: #ff4b4b;'>Harish Mohan</a></p>
""", unsafe_allow_html=True)